# To use this file, install the VS Code extension Rest-Client 
#   https://github.com/Huachao/vscode-restclient

@baseUrl = https://lll-laspub-func-demo.azurewebsites.net/api

### Start Orchestration
# @name startWorkRequest

POST {{baseUrl}}/TriggerRefreshPipeline HTTP/1.1
x-functions-key: *********==
