# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy IoT Function App Processor for the IoT Demo Project
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "FunctionDemo"
#  See ../Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: windows-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  branches:
    include: 
      - main
  paths:
    include:
      - logicapps.publisher.function
    exclude: 
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.bicep'

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/function-only-pipeline-template.yml
  parameters:
    variableGroupName: 'LASPublishDemo'
    environments: ['DEMO']
