# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Azure Resources and Application
# See readme file for info about variable group "FunctionDemo"
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger:
  #- none
  batch: true
  branches:
    include:
      - master
    exclude:
      - '**/*.md'
  paths:
    include:
      - 'logicapps.publisher.function/*'

pool:
  vmImage: 'ubuntu-latest'

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/infra-and-function-pipeline-template.yml
  parameters:
    variableGroupName: 'LASPublishDemo'
    environments: ['DEMO']
